### ISSUE TITLE
smtp-user-enum KeyError: 'from_mail' when too many errors

### ISSUE THREAD

**Issue by hawkinsst7** [cytopia/smtp-user-enum#10]
While attempting to enumerate a custom username list, the tool threw a KeyError when the server returned "too many errors". Supposedly this should be handled, but for some reason it's not in my case.

Installed with pip3

Below is a copy of output using a username list from seclist, just for demonstration.

```
[2036][user.kali: ~]$ /usr/local/bin/smtp-user-enum --version
smtp-user-enum 0.4.0 by cytopia

[2036][user.kali: ~]$ /usr/local/bin/smtp-user-enum -m RCPT -U /usr/share/seclists/Usernames/cirt-default-usernames.txt sneakycorp.htb 25 -V
Connecting to sneakycorp.htb 25 ...
[1/4] Connecting to sneakycorp.htb:25 ...
[1/4] Waiting for banner ...
220 debian ESMTP Postfix (Debian/GNU)
[1/4] Sending greeting: HELO test
[1/4] Waiting for greeting reply ...
250 debian
[1/4] Sending: MAIL FROM: user@example.com
[1/4] Waiting for MAIL FROM reply ...
250 2.1.0 Ok
Start enumerating users with RCPT mode ...
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:!root ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] !root                      501 5.1.3 Bad recipient address syntax
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:$ALOC$ ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] $ALOC$                     550 5.1.1 <$ALOC$>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:$SRV ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] $SRV                       550 5.1.1 <$SRV>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:$system ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] $system                    550 5.1.1 <$system>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:(NULL) ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] (NULL)                     501 5.1.3 Bad recipient address syntax
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:(any) ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] (any)                      501 5.1.3 Bad recipient address syntax
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:(created) ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] (created)                  501 5.1.3 Bad recipient address syntax
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:1 ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 1                          550 5.1.1 <1>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:11111111 ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 11111111                   550 5.1.1 <11111111>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:12.x ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 12.x                       550 5.1.1 <12.x>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:1502 ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 1502                       550 5.1.1 <1502>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:18140815 ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 18140815                   550 5.1.1 <18140815>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:1nstaller ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 1nstaller                  550 5.1.1 <1nstaller>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:2 ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 2                          550 5.1.1 <2>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:22222222 ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 22222222                   550 5.1.1 <22222222>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:30 ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 30                         550 5.1.1 <30>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:31994 ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 31994                      550 5.1.1 <31994>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:4Dgifts ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 4Dgifts                    550 5.1.1 <4Dgifts>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:5 ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 5                          550 5.1.1 <5>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:6.x ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 6.x                        550 5.1.1 <6.x>: Recipient address rejected: User unknown in local recipient table
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:7 ...
[Reconn 1/3] [Retry 1/5] Waiting for answer ...
[----] 7                          421 4.7.0 debian Error: too many errors
[Reconn 1/3] [Retry 1/5] Testing: RCPT TO:ADAMS ...
[Reconn 1/3] [Retry 2/5] Testing: RCPT TO:ADAMS ...
[Reconn 1/3] [Retry 3/5] Testing: RCPT TO:ADAMS ...
[Reconn 1/3] [Retry 4/5] Testing: RCPT TO:ADAMS ...
[Reconn 1/3] [Retry 5/5] Testing: RCPT TO:ADAMS ...
Traceback (most recent call last):
  File "/usr/local/bin/smtp-user-enum", line 560, in <module>
    main()
  File "/usr/local/bin/smtp-user-enum", line 537, in main
    enum_users(
  File "/usr/local/bin/smtp-user-enum", line 132, in enum_users
    conn["from_mail"],
KeyError: 'from_mail'

```

**Comment by cytopia** [comment]
@hawkinsst7 thanks for the bug report. I've opened a PR to mitigate this issue:

* PR: https://github.com/cytopia/smtp-user-enum/pull/11
* Branch: `release-0.5.0`

Can you go ahead and see if this works for you:
```
# switch to the branch with the fix
git checkout release-0.5.0
```
